### PR TITLE
Local build support

### PR DESCRIPTION
**Pull request by qparis**
- Added patches
- (Temporarely?) Disabled ncurse C++ librairie as it won't compile with macOS 10.13 SDK generated with XCode
- Begining of local building support (i.e. Use of phoenicis-winebuild inside an existing wine source root)

### CODE REVIEW

**Comment by qparis** [comment]
@Gcenx This is a small  update to allow building a local directory directly: 

It works like this: 
python3.7 phoenicis-make.py --wine-src=/Users/qparis/Desktop/wine/ --environment=wine_osxcross/linux/amd64 --os=darwin --architecture=x86on64

**Comment by Gcenx** [comment]
Ncurses c++ builds just fine for me, did you package the SDK by running the provided script from OSXCROSS as it grabs grabs the c++ headers and man pages from Xcode and bundles them into the packaged SDK

If you grabbed SDK and packaged it manually then here is a workaround
```
cp -r /usr/include/c++/v1 /opt/osxcross/SDK/MacOSX10.13.sdk/usr/include/c++
```

**Comment by qparis** [comment]
Yep, this is what I did.
Is the c++ library needed by wine?

**Comment by Gcenx** [comment]
Wine doesn't use c++ only gnuC98

**Comment by qparis** [comment]
So we can safely remove this support, right?

**Comment by Gcenx** [comment]
This could cause issues with the macports dependencies were using as that was build with ncurses c++ mode enabled, were only building it ourselves to avoid the database not accessible errors.

As we have previously committed an SDK would it be acceptable for me to commit my working copy of the 10.13 SDK?


I took a while to answer so I could rebuild the image from scratch and c++ component of Ncurses indeed builds for me without issue

**Comment by qparis** [comment]
> This could cause issues with the macports dependencies were using as that was build with ncurses c++ mode enabled, were only building it ourselves to avoid the database not accessible errors.

I'm not sure it is related. This error occurs when the terminal file is not accessible 


> As we have previously committed an SDK would it be acceptable for me to commit my working copy of the 10.13 SDK?

I was not aware we did that ; we should not have. The SDK is copyrighted, we are not allowed to redistribute it afaik

**Comment by Gcenx** [comment]
What I’m saying is if a macports dependency attempts to call Ncurses c++ comportment it will fail after this change.

https://github.com/PhoenicisOrg/phoenicis-winebuild/commit/bdd8a5e186d9ea7460ed1e247ff3e438843f66e8

**Comment by qparis** [comment]
This was a mistake... 

> What I’m saying is if a macports dependency attempts to call Ncurses c++ comportment it will fail after this change.

I'm not sure ; if the library does not exists, I don't see how the error can appear because the error is displayed by the library

**Comment by Gcenx** [comment]
On my system c++ is working just fine
```
testing o32-clang++ -stdlib=libc++ -std=c++11 ... works
testing o64-clang++ -stdlib=libc++ -std=c++11 ... works

testing o32-clang ... works
testing o32-clang++ ... works

testing o64-clang ... works
testing o64-clang++ ... works
```

And Ncurses with c++ components builds without issue, wine-5.0.1 built without issue, so definitely something wrong with how the SDK your using was packaged, I went an additinal step and included QuickTime.framework from MacOSX10.11.sdk since wine still uses this on macOS

**Comment by qparis** [comment]
I  have the same result when testing against different clang version. The SDK is packaged with the last stable version of xcode. I suspect it is more a problem of compatibility between the different xcode version which can include different versions of C++ headers I guess

**Comment by Gcenx** [comment]
Modify the sdk packing script to point to a subfolder and place Xcode.app (9.4.1) within that and run the script

And yes the c++ headers are linked to the version of Xcode

**Comment by qparis** [comment]
Ok it seems to work!

**Comment by Gcenx** [comment]
Testing the commit locally and it's compiling currently using the following command
```
python3 python3.7 phoenicis-make.py --wine-src=/Users/qparis/Desktop/wine/ --environment=wine_osxcross/linux/amd64 --os=darwin --architecture=x86on64 --build
```

Without `--build` it didn't attempt to compile the source, that doesn't make much sense from a user perspective if I'm calling `python3.7 phoenicis-make.py --wine-src=/Users/qparis/Desktop/wine/ --environment=wine_osxcross/linux/amd64 --os=darwin --architecture=x86on64` it shouldn't require `--build`

**Comment by qparis** [comment]
Yes this is perfectly normal. Some people may just want to apply patches, or just connect to the ready container to build manually, or any other feature we support later on

**Comment by Gcenx** [comment]
If the plan is to add additional features that makes sense.

I tested this and it builds but doesn’t output the build (guess this needs to be added still)

**Comment by qparis** [comment]
I think we should indeed add an extra volume for the output yep. But in general, in this mode, I tend to run wine directly from the directly while I'm modifying its code source with an IDE

**Comment by Gcenx** [comment]
We also need to add darling-dmg since MoltenVK now only ships within dmg files

**Comment by qparis** [comment]
I think dmg can be exctracted on linux ; they are juste img files basically

**Comment by Gcenx** [comment]
Dmg are UDIF and HFS, the advantage of using darling-dmg is we can mount the dmg and grab the files we need from it without needing it extract the image

**Comment by qparis** [comment]
Even in a docker image? I think you can extract exactly what you need with 7zip

**Comment by plata** [comment]
Can the branch be deleted? Shall we configure the settings such that merged branches are deleted automatically?

**Comment by qparis** [comment]
Yes

**Pull request merged**
