### PR TITLE
Update runtime code

### PR DESCRIPTION
**Pull request by ImperatorS79**
That way we should catch all the needed .so more easily.

### CODE REVIEW

**Comment by qparis** [comment]
This looks dangerous. Won't you end up with far too much dependencies?

**Comment by ImperatorS79** [comment]
It is a change of how I see this script. Instead of adding lib one by one, we exclude the one we do not need. I think this will require way less work this. I did a week ago try to simply add every lib needed by crayon physics to the runtime, it took me an amount of time far too big (for what I am able to give to this) and I did not finished it. While with this I have all libs required by crayon physics (I still a lib to add actually, but it is in a subfolder).

The .zip I obtain is 135 MB, which is 3 x times the size of the current runtime (note it is expected that the runtime would grow since it is currently missing a lot of lib (my crayon physics experiments)).

**Comment by qparis** [comment]
Could we automatically detect what lib is needed thanks to ldd instead?

**Comment by ImperatorS79** [comment]
You would have to run ldd all the wine .so and bin, then to all .so that ldd would return. The only libs you would exclude at the end would be libc6 libs (provided by the distribution because of the hardcoded path of ld-linux.so and the link with the kernel) and graphics driver.

**Comment by qparis** [comment]
Yep

**Pull request merged**
