### PR TITLE
Add a league of legends distribution

### PR DESCRIPTION
**Pull request by ImperatorS79**
How can I apply the patches on top of wine-staging @qparis ?

### CODE REVIEW

**Comment by qparis** [comment]
Use ApplyWineStagingPatches hook (see wine staging distribution)

**Comment by ImperatorS79** [comment]
And what is the purpose of `extends `?

When this is merged, would you mind trying to build wine-4.14 with this :grin: ?

**Comment by qparis** [comment]
extends is just informative for the moment 

No problem for building wine-4.14. Can you check that it compiles locally?

**Comment by ImperatorS79** [comment]
I meant to build wine-4.14 with the patches here ^^.
I am not able to test right now unfortunately.

**Comment by ImperatorS79** [comment]
What is the syntax of builder.build for this ? Example files are not consistent between each other.

**Comment by Gcenx** [comment]
@ImperatorS79

`builder.build("league-of-legends", "wine-4.15", "linux", "amd64")`

**Comment by ImperatorS79** [comment]
@Gcenx Does not work:
```
Traceback (most recent call last):
  File "/home/vmachine/phoenicis-winebuild/packagers/PhoenicisWinePackageCreator.py", line 62, in build
    builder.build(operating_system, arch, version, distribution, distribution_parameters["source"])
  File "/home/vmachine/phoenicis-winebuild/builders/WineBuilder.py", line 38, in build
    self.prepare(operating_system, arch, version, distribution, repository)
  File "/home/vmachine/phoenicis-winebuild/builders/WineBuilder.py", line 24, in prepare
    self._apply_patches(operating_system)
  File "/home/vmachine/phoenicis-winebuild/builders/WineBuilder.py", line 57, in _apply_patches
    self._apply_patch(patch)
  File "/home/vmachine/phoenicis-winebuild/builders/WineBuilder.py", line 73, in _apply_patch
    self.container.run(["sh", "-c", "git apply --3way /root/patches/" + patch["name"] + "/*.diff"], workdir="/root/wine-git")
  File "/home/vmachine/phoenicis-winebuild/core/Container.py", line 87, in run
    raise Exception("Builder returned a non-zero code: " + str(exit_code))
Exception: Builder returned a non-zero code: 1
Cleaning container
```

**Comment by Gcenx** [comment]
@ImperatorS79 hum weird, are you able to launch any of the examples?

Here is the example I pulled the line from, this was created from Darwin examples I had updated previously and were working last I checked.
`#!/usr/bin/env python
from packagers.PhoenicisWinePackageCreator import PhoenicisWinePackageCreator

builder = PhoenicisWinePackageCreator()

builder.build("upstream", "wine-4.9", "linux", "amd64")
`

Could you upload the  builder log, Or did it not even get the the stage of making a log?

**Comment by ImperatorS79** [comment]
Unfortunately it errors:
001.diff
002.diff
error: dlls/ntdll/virtual.c: does not match index

**Comment by ImperatorS79** [comment]
I think I am missing a patch, stay tuned ^^.

**Comment by ImperatorS79** [comment]
So I did not miss a patch, I think I will recreate a diff file myself...

**Comment by ImperatorS79** [comment]
@qparis Manually applying the patches using `patch -p1 -i 0001.diff` works.
So I do not know why it does not work here. Do you have any idea ?

**Comment by qparis** [comment]
What if you use git apply command?

**Comment by ImperatorS79** [comment]
It works if I do `git apply 0001.diff` then `git apply 0002.diff`

**Comment by qparis** [comment]
What about git apply --3way?

**Comment by ImperatorS79** [comment]
Then it does not work.

**Comment by qparis** [comment]
This is why

**Comment by ImperatorS79** [comment]
Then could it be possible to add an option to not use this --3way so that it works ?

**Comment by qparis** [comment]
The best would be to reformat the patch imho

**Comment by ImperatorS79** [comment]
And how can I do that ?

**Comment by qparis** [comment]
Apply it, and re-generate it with git diff

**Comment by madoar** [comment]
Are there any updates?

**Comment by ImperatorS79** [comment]
I have no time to check this currently and I do not even kn ow if it is till needed.

**Comment by Gcenx** [comment]
@ImperatorS79 is a custom distribution needed anymore?

**Comment by ImperatorS79** [comment]
No idea.

**Pull request closed without merging**
