### PR TITLE
Compile SDL2 and merge

### PR DESCRIPTION
**Pull request by Gcenx**
Download SDL2-2.0.9 source code, built 32bit, build 64bit & lipo into a Universal libSDL2-2.0.0.dylib

### CODE REVIEW

**Comment by Gcenx** [comment]
> Looks good. Can you confirm that you can build a dos_support build and that it works?

Honestly I have never tried to build anything outside of "interactive_builder.py" and no example shows how to build a "dos_support" build I tried but I properly did something wrong.
Same for winecx no idea how to build that also.

**Comment by qparis** [comment]
You can run Python and type (line by line)

> from core.Container import Container
> from core.Environment import Environment
> from builders.WineBuilder import WineBuilder
> 
> environment = Environment("wine_osxcross", "linux", "x86")
> environment.build()
> 
> container = Container(environment)
> container.start()
> 
> builder = WineBuilder(container)
> builder.build("darwin", "dos_support", "wine-4.0")
> builder.archive("custom_wine.tar.gz")

**Comment by qparis** [comment]
(and terminates by container.close())

**Comment by Gcenx** [comment]
This is what I get doing that


```
Traceback (most recent call last):
  File "examples/example_osx_dos_support.py", line 15, in <module>
    builder.build("darwin", "dos_support", "wine-4.0")
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/builders/WineBuilder.py", line 34, in build
    self.container.run_script(script)
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/core/Container.py", line 129, in run_script
    self.put_file(script, "/tmp/", "script")
  File "/Users/gcenx/Documents/GitHub/phoenicis-winebuild/core/Container.py", line 106, in put_file
    with open(local_file, mode='rb') as scriptfile:
FileNotFoundError: [Errno 2] No such file or directory: 'builders/scripts/builder_darwin_dos_support_wine'
```

**Comment by qparis** [comment]
When is your current directory?

**Comment by Gcenx** [comment]
/Users/gcenx/Documents/GitHub/phoenicis-winebuild/

The directly was set as per the readme and instead of launching the interactive_builder I launched the new example

**Comment by qparis** [comment]
My bad! It is 

`builder.build("darwin", "x86", "wine-4.0", "dos_support")`

**Comment by Gcenx** [comment]
I can try again after work.
But I think I remember doing that and it didn’t work.
Wine compiled but the dos_support hooks didn’t run at the end

**Comment by qparis** [comment]
Ok, it would be interesting to know so that we can debug it

**Comment by Gcenx** [comment]
> How do you know that dos_support hooks does not work?

As nothing that would have been added by using it is precent within the outputted build

**Comment by qparis** [comment]
So you do not have any dosbox binaries inside bin/?

**Comment by Gcenx** [comment]
> So you do not have any dosbox binaries inside bin/?

That's correct.

**Comment by qparis** [comment]
No error indication that would help to understand why?

**Comment by qparis** [comment]
Yes this is normal. The hooks need to be passed to the WineBuilder class that is too low level to detect it. 

You need to use PhoenicisWinePackageCreator which will do everything automatically for you 

So:

```
from packagers import PhoenicisWinePackageCreator
phoencisWinePackager = PhoenicisWinePackageCreator()
phoencisWinePackager.build("dos_support", "wine-4.0", "darwin", "x86")
```
This will create a dist/binaries and dist/logs directories where everything is in

**Comment by Gcenx** [comment]
> Yes, same principle

Mind posting the above as a working example script that I can just use once I'm home?

**Comment by qparis** [comment]
I have updated the interactive builder

**Comment by Gcenx** [comment]
Ok I will grab that change on my side before testing again. Also might wanna allow 4 releases to be listed with the interactive builder also

**Comment by Gcenx** [comment]
> Great!

Since I submitted this as a patch I don’t want to try updating the interactive builder to support wine-4 builds.

Also would it be possible to also update the examples to use the PhoencisWinePackageCreator inseatd of winebuild so it’s possible to build dos_support and cx and not need to use interactivebuilder?

**Comment by qparis** [comment]
Should be good :-)

**Pull request merged**
