### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by Gcenx**
- Updated interactive_builder.py
- Updated fix_imports.sh
- Updated builder_darwin_x86_wine
- Updated builder_darwin_amd64_wine
- Updated example_osx.py
- Added WineCX examples

### CODE REVIEW

**Comment by qparis** [comment]
Amazing

**Comment by Gcenx** [comment]
> Amazing

Thanks


I had a little more but I wasn’t sure the changes would be wanted;
- Changed all examples to use packing like WineCX (consistency with binary/log locations)
- Always apply cmd+q quit for darwin builds (to be consistent with native macOS applications)

**Comment by qparis** [comment]
Not entireley sure for the first one: As long as wine is modifed from upstream, winehq won't accept any support. I think upstream should be vanilla

**Comment by Gcenx** [comment]
> Not entireley sure for the first one: As long as wine is modifed from upstream, winehq won't accept any support. I think upstream should be vanilla

Ok so let’s not use these patches by default then to be safe then, since staging is also supported by winehq in an official/unoffical way.


What about the updated examples?
All I did was have them use the same format used by the WineCX examples.

**Comment by qparis** [comment]
+1 for the examples

**Comment by qparis** [comment]
We can also create a custom distribution

**Pull request merged**
