### PR TITLE
Fixed typos on strings 83, 84, 130

### PR DESCRIPTION
**Pull request by kant**
* plus some minor formatting proposals

### CODE REVIEW

**Comment by qparis** [comment]
Thank you for the contribution. However, the checks seems to have failed.

**Comment by plata** [comment]
@qparis have a look at the error. Actually, I would not use a language flag there myself. Maybe we should change the configuration of Codacy for this issue.

**Comment by qparis** [comment]
I do not know what are language flags useful for

**Comment by plata** [comment]
It would provide code highlighting for the selected language (e.g. if you say "Javascript"). However, that doesn't make too much sense in this case.

**Pull request merged**
