### PR TITLE
Clang refacto

### PR DESCRIPTION
**Pull request by qparis**

### CODE REVIEW

**Comment by Gcenx** [comment]
https://github.com/PhoenicisOrg/phoenicis-winebuild/blob/7484aeab2172384e6ddf2df881bc38ea6e7191c9/environments/linux-amd64-wine_osxcross#L46 needs to be moved above https://github.com/PhoenicisOrg/phoenicis-winebuild/blob/7484aeab2172384e6ddf2df881bc38ea6e7191c9/environments/linux-amd64-wine_osxcross#L38

Change the prefix to /opt/local and for make install DESTDIR="/build/$ARCH/" to install into the desired locations, after this a lipo stage will be required to merge the dylibs into a single universal library.

**Comment by Gcenx** [comment]
Correction move

https://github.com/PhoenicisOrg/phoenicis-winebuild/blob/7484aeab2172384e6ddf2df881bc38ea6e7191c9/environments/linux-amd64-wine_osxcross#L55

Above

https://github.com/PhoenicisOrg/phoenicis-winebuild/blob/7484aeab2172384e6ddf2df881bc38ea6e7191c9/environments/linux-amd64-wine_osxcross#L38

**Comment by qparis** [comment]
In fact, /root/osxcross/target/macports/pkgs/opt/local does not seem to exist yet

**Comment by Gcenx** [comment]
Ah yes as currently no packages were installed by osxcross it wouldn’t exit yet.

Ive forgotten you moved those above the package install section

**Comment by Gcenx** [comment]
I don't see any issues with this now but still would be a good idea to test it out, just expect issues with installing prebuilt macports packages.

If this section works then it would be a good idea to do the same for other needed libraries so packages.macports can be avoided.

**Comment by qparis** [comment]
It does no longer work..

When I built gnutls, i get 

#40 12.37 ***
#40 12.37 *** gmp was not found.
#40 12.37

**Comment by Gcenx** [comment]
After each component is built it needs to be make universal and have the headers installed into /opt/local

**Comment by qparis** [comment]
Ok, better

**Comment by qparis** [comment]
@Gcenx gnutls builds correctly on my local environment. I propose to merge this as it is more stable than current main branch thanks to your suggestions. 

I'll open other merge request later to improve the code

**Comment by Gcenx** [comment]
@qparis it would also a good idea to do the same for ncurses/sdl2/faudio

The sdl2 patch and be dropped when bumped, FAudio doesn’t need any patch unless 10.8 support is desired but below 10.9 is not really worth the effort.

Then again due to the lack of required universal packages from Macports it might be time to build the minimum required libraries directly.

So freetype/png/jpeg etc, ignoring gstreamer1 along with it’s plugins as those will lead to nightmares….


Having gnutls resolves tons of annoyances and when using WineCX builds allows for a working Steam client. Upstream wine on macOS for example doesn’t use any of the macOS networking libraries anymore as we found they were useless instead opting to just use gnutls. This also helped with the PE transition.

**Comment by qparis** [comment]
Yes, I will do the other librairies just afterwards

**Comment by qparis** [comment]
```
configure: libgnutls 64-bit development files too old, bcrypt encryption won't be supported.
```

Any idea?

**Comment by Gcenx** [comment]
Hum this could be that upstream wine does not correctly detect gnutls next, I'm using the stable branch without issue.

**Comment by qparis** [comment]
I'm using cxoffice wine

**Comment by Gcenx** [comment]
Not sure I can use this on the M1 mac, I'm using macports running under Rosetta2. I'm assuming the issue is gnutls next changed things around and wine doesn't detect this correctly it does detect the current stable gnutls properly.

**Comment by qparis** [comment]
I think you can but it might be quite slow. 

One next step for me is to make phoenicis-winebuild compatible with kubernetes so we can easily use any cloud provider to build wine binaries

**Comment by Gcenx** [comment]
@qparis managed to test this out as my Intel mac is now free and phoenicis-winebuild winecx-20.0.0 configure gives me the same issue even when using the stable version of gnutls, however wine-stable-6.0.1 doesn't have this problem so all I think think is this check was fixed in a later wine version making it work correctly.

**Comment by Gcenx** [comment]
Leaving a winecx20.0.0 build to run where I’m skipping the related check _hoping_ this will complete.

**Comment by qparis** [comment]
Do you remember why vk3d is disabled?

**Comment by Gcenx** [comment]
> Do you remember why vk3d is disabled?

The reason for this was vkd3d was utterly useless on macOS.

**Comment by qparis** [comment]
What is the reason?

**Comment by Gcenx** [comment]
> What is the reason?

MoltenVK doesn’t provide the needed Vulkan extensions for DX12.

**Comment by qparis** [comment]
Weird, it seems that codeweavers has announced DX12 support

**Comment by Gcenx** [comment]
> Weird, it seems that codeweavers has announced DX12 support

That’s not for macOS but Linux, they announced using WineD3D Vulkan for DirectX10/11 on macOS however still awaiting a resolution for my ticket that’s related to this.

**Pull request merged**
