### PR TITLE
[WIP] Update FreeBSD environment

### PR DESCRIPTION
**Pull request by ImperatorS79**
Splitted the dockerfile into multiple .sh:
- symlink.sh and symlink32.sh fix bad symlinks from the .iso
- extractSDK, which extracts the SDK for both architecture
- build and build32 which build a 64 bits and a 32 bits compiler
- installdeps and installdeps32, which simply download the .txz from the right mirror and ""install"" it.

I aslo added to env variable VERSION for freebsd version and GCCVERSION .

The 32 bits part is currently untested.

I still need to write a builder to see if:
- more symlink are needed to be fixed
- which .txz are needed
- if this works ^^

Comments are welcome.

### CODE REVIEW

**Comment by qparis** [comment]
I don't think it is a good practice to separate too much in several files, because you won't take advantage on docker snapshots between compilation steps

**Comment by ImperatorS79** [comment]
Like this ?

**Comment by qparis** [comment]
Looks good! Does it work?

**Comment by ImperatorS79** [comment]
Did not test. VM too small ^^.

**Comment by plata** [comment]
Should we maybe have some build images on DockerHub?

**Comment by Gcenx** [comment]
> Should we maybe have some built images on DockerHub?

That would be a good idea once you guys are happy with the project, I know that would be a simple solution for later usage.

**Comment by qparis** [comment]
Let's test

**Pull request merged**
