### PR TITLE
Fix undetected libgnutls (missing libgmp), libncurses and others

### LINKED ISSUE #97: Check why wine fails to load libgnutls
One should check what `SONAME_LIBGNUTLS` wine expects in `wine/dlls/bcrypt/gnutls.c`.

### PR DESCRIPTION
**Pull request by ImperatorS79**
Fix #97.

@qparis You know what to do ;-).

EDIT: no need to have libbsd and libncurses in the .deb nox ^^.

### CODE REVIEW

**Comment by ImperatorS79** [comment]
Please wait to merge this because I fixed the libncurses problem.

**Comment by ImperatorS79** [comment]
Fixed libfreetype :+1:.

**Comment by qparis** [comment]
How?

**Comment by ImperatorS79** [comment]
Seems missing libz makes everything crash.

**Pull request merged**
