### PR TITLE
Copy libidn from /lib

### PR DESCRIPTION
**Pull request by ImperatorS79**
Reported by @Zemogiter and @Kreyren in The Sims 2.

Again @qparis you will have to update the .tar.gz and the .json.

### CODE REVIEW

**Comment by ImperatorS79** [comment]
Ok so you added the entry to the .json. I did not expect that for the runtime code when I have written it. I thought you will just modify the original json. So it will not work as expected :skull:.

Is there any reason to do so ?

**Comment by qparis** [comment]
To ensure backward compatibility, old runtime are kept

**Comment by ImperatorS79** [comment]
I still do not see the point here since it is an alpha and the runtime was modified by adding libs. I mean phoenicis will always only download the latest version, so you could keep the old runtimes somewhere, but not in the json.

**Comment by qparis** [comment]
Keep in mind that the json generation process is automated ; I'm not making difference between different modifications. 

Later, we will be able to enforce a given runtime for an old wineversion but this is not a priority

**Comment by ImperatorS79** [comment]
And in the option where there is multiple runtimes in the json, how do I determine which one to download ?

**Comment by qparis** [comment]
The most recent date for the moment

**Comment by ImperatorS79** [comment]
The date is stored in name, right ? I will open an issue about that on the script repo.

**Pull request merged**
